[Defines]
    workdir = "C:\\workspace\\MinPlatform\\edk2-platforms\\Platform\\Intel"
    projectname = "MinKabylake"
    workspace = "C:\\workspace\\MinPlatform"
    cache_dir = ""

[[Repo]]
    name = 'edk2'
    git = 'https://github.com/tianocore/edk2.git'
    branch = 'master'
    version = 'head'
[[Repo]]
    name = 'edk2-platform'
    git = 'https://github.com/tianocore/edk2-platforms.git'
    branch = 'master'
    version = 'head'
[[Repo]]
    name = 'edk2-non-osi'
    git = 'https://github.com/tianocore/edk2-non-osi.git'
    branch = 'devel-MinPlatform'
    version = 'head'
[[Repo]]
    name = 'FSP'
    git = 'https://github.com/IntelFsp/FSP.git'
    branch = 'master'
    version = 'head'    

[Basic]
    [[Basic.step]]
        name = "CleanBuild"
        depends = []
        [Basic.step.command]
            cmd = 'py'
            parameters = ["-3", "build_bios.py", "--cleanall"]
        output_type = ['File']
    [[Basic.step]]
        name = "BuildPlatform"
        depends = ["CleanBuild"]
        [Basic.step.command]
            cmd = 'py'
            parameters = ["-3", "build_bios.py", "-p", "KabylakeRvp3"]
        output_type = ['File']
        
#[OtherOption]
#[[OtherOption.step]]
#    name = "CleanBuild"
#    depends = []
#    [OtherOption.step.command]
#        cmd = 'py'
#        parameters = ["-3", "build_bios.py", "--cleanall"]
#    output_type = ['File']
#[[OtherOption.step]]
#    name = "BuildPlatform"
#    depends = ["CleanBuild"]
#    [OtherOption.step.command]
#        cmd = 'py'
#        parameters = ["-3", "build_bios.py", "-p", "KabylakeRvp3"]
#    output_type = ['File']
    
