[Defines]
    workdir = "C:\\workspace\\MinPlatform\\edk2-platforms\\Platform\\Intel\\PurleyOpenBoardPkg\\BoardMtOlympus"
    projectname = "MinPurley"
    workspace = "C:\\workspace\\MinPlatform"
    cache_dir = ""

[[Repo]]
    name = 'edk2'
    git = 'https://github.com/tianocore/edk2.git'
    branch = 'master'
    version = 'head'
[[Repo]]
    name = 'edk2-platform'
    git = 'https://github.com/tianocore/edk2-platforms.git'
    branch = 'master'
    version = 'head'
[[Repo]]
    name = 'edk2-non-osi'
    git = 'https://github.com/tianocore/edk2-non-osi.git'
    branch = 'devel-MinPlatform'
    version = 'head'

[Basic]
    [[Basic.step]]
        name = "SetupEnv"
        depends = []
        [Basic.step.command]
            cmd = "GitEdk2MinMtOlympus.bat"
        output_type = ['EnvVar','File']
    [[Basic.step]]
        name = "BuildPlatform"
        depends = []
        [Basic.step.command]
            cmd = 'bld'
        output_type = ['File']
    
